version: '3.8'

services:
  # The Flask Python API service
  back-end:
    image: softy-pinko-back-end:task4
    build:
      context: ./task4-back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"

  # The Nginx Web Server service
  front-end:
    image: softy-pinko-front-end:task4
    build:
      context: ./task4-front-end
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - back-end
